http:
  host: "localhost"
  port: "8081"
soap:
  wsdl: "http://34.86.136.216:6063/ws/employees.wsdl"
  service: "EmployeePortService"
  port: "EmployeePortSoap11"
  address: "http://34.86.136.216:6063/ws"